name: Eventos02_Participantes_FTPv2

on:
  schedule:
    - cron: '15 4 * * *'   # 04:15 UTC (ajusta según tu Módulo 1)
  workflow_dispatch: {}

jobs:
  participants:
    runs-on: ubuntu-22.04
    env:
      TZ: Europe/Madrid
      HEADLESS: "true"
      OUT_DIR: "./output"
      PER_EVENT_MAX_S: "180"
      PER_PAGE_MAX_S: "35"
      MAX_RUNTIME_MIN: "40"
      LIMIT_EVENTS: "2"   # procesa 2 eventos

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install Chrome & Chromedriver
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip ca-certificates curl
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome-stable --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+')
          echo "Chrome version: $CHROME_VERSION"

          CHROMEDRIVER_URL="https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${CHROME_VERSION}/linux64/chromedriver-linux64.zip"
          if wget -q --spider "$CHROMEDRIVER_URL"; then
            echo "Descargando ChromeDriver ${CHROME_VERSION}"
            wget -q -O chromedriver.zip "$CHROMEDRIVER_URL"
            unzip -o chromedriver.zip
            sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
            sudo chmod +x /usr/local/bin/chromedriver
            rm -rf chromedriver.zip chromedriver-linux64
          else
            echo "Fallback: chromium-chromedriver"
            sudo apt-get install -y chromium-chromedriver
            sudo ln -sf /usr/bin/chromedriver /usr/local/bin/chromedriver
          fi

          which google-chrome-stable
          which chromedriver
          google-chrome-stable --version
          chromedriver --version

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install webdriver-manager || true

      - name: Ensure output dirs
        run: |
          mkdir -p "${OUT_DIR}"
          mkdir -p "${OUT_DIR}/participants"

      - name: Ensure 01events.json (pull from FTP or generate)
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}
          FLOW_EMAIL: ${{ secrets.FLOW_EMAILRQ }}
          FLOW_PASS: ${{ secrets.FLOW_PASSRQ }}
          HEADLESS: "true"
          MAX_SCROLLS: "12"
          SCROLL_WAIT_S: "2.0"
          LIMIT_EVENTS: "2"
        run: |
          set -e
          mkdir -p ./output

          if [ -f "./output/01events.json" ]; then
            echo "Ya existe ./output/01events.json"
          else
            if [ -n "$FTP_SERVER" ] && [ -n "$FTP_USERNAME" ] && [ -n "$FTP_PASSWORD" ] && [ -n "$FTP_REMOTE_DIR" ]; then
              REMOTE_DIR="${FTP_REMOTE_DIR}/Competiciones/EventosProx/Flow/data"
              BASE_URL="ftp://${FTP_SERVER}${REMOTE_DIR}"
              echo "Intentando descargar 01events.json desde ${BASE_URL}"
              curl --fail --ssl-reqd \
                   --user "${FTP_USERNAME}:${FTP_PASSWORD}" \
                   -o "./output/01events.json" \
                   "${BASE_URL}/01events.json" || echo "No se pudo descargar de FTP"
            fi
          fi

          if [ ! -f "./output/01events.json" ]; then
            echo "Generando 01events.json ejecutando flow_events.py"
            python ./flow_events.py
          fi

          if [ ! -f "./output/01events.json" ]; then
            echo "Falta ./output/01events.json (ni FTP ni generación local)"
            exit 1
          fi
          ls -la ./output/01events.json

      - name: Run participants scraper (Módulo 2)
        timeout-minutes: 90
        env:
          FLOW_EMAIL: ${{ secrets.FLOW_EMAILRQ }}
          FLOW_PASS:  ${{ secrets.FLOW_PASSRQ }}
        run: |
          echo "=== EXTRAER PARTICIPANTES ==="
          python ./flow_participants.py
          echo "=== FIN EXTRAER PARTICIPANTES ==="
          ls -la "${OUT_DIR}" || true
          ls -la "${OUT_DIR}/participants" || true

      - name: Verify generated files
        run: |
          if [ -f "./output/02participants.json" ]; then
            echo "OK 02participants.json"
          else
            echo "NO 02participants.json"
            exit 1
          fi

      - name: Compress outputs (aggregated + per-event)
        run: |
          set -e
          gzip -9 -c "./output/02participants.json" > "./output/02participants.json.gz"
          shopt -s nullglob
          for f in ./output/participants/02p_*.json; do
            gzip -9 -c "$f" > "${f}.gz"
          done
          ls -la ./output/*.gz || true
          ls -la ./output/participants/*.gz || true

      - name: Upload to FTP (aggregated + per-event)
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}
        run: |
          set -e
          if [ -z "$FTP_SERVER" ] || [ -z "$FTP_USERNAME" ] || [ -z "$FTP_PASSWORD" ] || [ -z "$FTP_REMOTE_DIR" ]; then
            echo "Variables FTP no configuradas"
            exit 1
          fi
          REMOTE_DIR="${FTP_REMOTE_DIR}/Competiciones/EventosProx/Flow/data"
          BASE_URL="ftp://${FTP_SERVER}${REMOTE_DIR}"

          curl --fail --ssl-reqd --ftp-create-dirs --disable-epsv --ftp-skip-pasv-ip \
               --user "${FTP_USERNAME}:${FTP_PASSWORD}" \
               --upload-file "./output/02participants.json.gz" \
               "${BASE_URL}/02participants.json.gz"

          curl --fail --ssl-reqd \
               --user "${FTP_USERNAME}:${FTP_PASSWORD}" \
               --upload-file "./output/02participants.json" \
               "${BASE_URL}/02participants.json"

          shopt -s nullglob
          for f in ./output/participants/02p_*.json.gz; do
            base=$(basename "$f")
            curl --fail --ssl-reqd --ftp-create-dirs --disable-epsv --ftp-skip-pasv-ip \
                 --user "${FTP_USERNAME}:${FTP_PASSWORD}" \
                 --upload-file "$f" \
                 "${BASE_URL}/participants/${base}" || echo "Fallo subiendo ${base}"
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: participantes-json
          path: |
            ./output/02participants.json
            ./output/02participants.json.gz
            ./output/participants/*.json
            ./output/participants/*.json.gz
          retention-days: 7
